### ISSUE TITLE
Display number of books in the database

### ISSUE THREAD

**Issue by Jake-Fischer** [Jake-Fischer/readinglist#10]
Add a menu option to display the total number of books in the database. The total is the sum of the read, and unread books. So if there are 10 read books and 14 unread books, your program will output a message like

"There are 24 books in the database"

Hint: what code already exists that will help?

**Comment by mkhalil7625** [comment]
def book_count(self):

**Comment by ew3361zh** [comment]
@mkhalil7625 I like the way it's working! 
-I think I would capitalize all the words in the menu option title to match the style of the other menu options (So right now the second word reads as "total" and I think it should be "Total" to match everything else).
-I wonder about adding an if/else block to account for the grammar of whether there is 1 book or multiple books/zero books. So in main book_count() you could have: 
if count == 1:
print('There is 1 book in the database')
else:
print(f'There are {count} books in the database')
What do you think?

**Comment by mkhalil7625** [comment]
closed
